#!/bin/bash

sudo apt install python3-pi python3-libgpiod
sudo pip install adafruit-circuitpython-dht
sudo pip install RPi.gpio


wget https://raw.githubusercontent.com/Wildlife-Systems/sensor-dht11/main/sensor-dht11
chown root:root sensor-dht11
chmod +x sensor-dht11
mv sensor-dht11 /usr/bin

sudo mkdir -p /var/aao/sensors
wget https://raw.githubusercontent.com/Wildlife-Systems/sensor-dht11/main/dht11
chown root:root dht11
mv dht11 /var/aao/sensors
