#!/usr/bin/env python3
import sys

if len(sys.argv) == 2:
  if sys.argv[1] == "identify":
    sys.exit(60)
  if sys.argv[1] == "list":
    print("temperature")
    print("humidity")
    sys.exit(0)

import time
import board
import adafruit_dht
import os
import json

dhtDevice = adafruit_dht.DHT11(board.D4)

#Get template JSON respone
stream = os.popen('sc-prototype')
output = stream.read()

temperature = json.loads(output)
humidity = json.loads(output)

temperature["sensor"] = "dht11_temperature"
temperature["measures"] = "temperature"
temperature["unit"] = "Celsius"

humidity["sensor"] = "dht11_humidity"
humidity["measures"] = "humidity"
humidity["unit"] = "percentage"

while True:
    try:
        temperature["value"] = dhtDevice.temperature
        humidity["value"] = dhtDevice.humidity
        dhtDevice.exit()
        break
    except RuntimeError as error:
        # Errors happen fairly often, DHT's are hard to read, just keep going
        print(error.args[0])
        time.sleep(2.0)
        continue
    except Exception as error:
        dhtDevice.exit()
        raise error

print("[",json.dumps(temperature),",",json.dumps(humidity),"]")
